server:
  port: 8888

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ilnar-Safiullin/ConfigSavePublicAston
          default-label: master